### ISSUE TITLE
Broken status/linkuptime functions on FritzBox cabel models 

### ISSUE THREAD

**Issue by rustyricky** [mcktr/check_tr64_fritz#30]
Hello,

the script always returns  `UNKNOWN - Could not get a response | status=3` for me.
`-d` claims I'm using the wrong password, which I can rule out as I'm using the same credentials to log into the webinterface using copy&paste:

```
./check_tr64_fritz -d -h fritz.box -p 49443 -u redacted -P redacted -f status

<HTML>
  <HEAD>
    <TITLE>401 Unauthorized (ERR_ACCESS_DENIED)</TITLE>
  </HEAD>
  <BODY>
    <H1>401 Unauthorized</H1><BR>ERR_ACCESS_DENIED<HR><B>Webserver</B> Sat, 11 Nov 2017 15:46:31 GMT
  </BODY>
</HTML>
```

Oddly enough the reponse looks very different when I remove `-d`:

```
./check_tr64_fritz -h fritz.box -p 49443 -u redacted -P redacted -f status


<?xml version="1.0"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <s:Body>
    <s:Fault>
      <faultcode>s:Client</faultcode>
      <faultstring>UPnPError</faultstring>
      <detail>
        <UPnPError xmlns="urn:dslforum-org:control-1-0">
          <errorCode>402</errorCode>
          <errorDescription>Invalid Args</errorDescription>
        </UPnPError>
      </detail>
    </s:Fault>
  </s:Body>
</s:Envelope>
```

Environment:
FritzBox 6360 Cable (Kabel Deutschland)
FRITZ!OS 06.54

**Comment by rustyricky** [comment]
Some functions seem to be working fine though:

Working: uptime, upstreamrate, upstream, downstreamrate, downstream
Broken: status (see OP), linkuptime (could not parse output)

**Comment by mcktr** [comment]
Hi.

you are using a Fritz!Box cable model and I guess that the information for the status and linkuptime function are not retrievable in the same way as on a "normal" Fritz!Box DSL model. 

Both functions (status and linkuptime) are using the same TR-064 request to get the information, basically they retrieve information about WAN PPP and this is the problem I guess, on a cable model you don't have this, because the connection method is not PPPoE.

I don't have access to an Fritz!Box cable model nor to a cable connection, so I can't looking into the details of the the TR-064 interface of such a Fritz!Box model. To figure out how they provide the needed information and for developing a fix for it, I could need your help (if you want) :)

First step is to figure out which TR-064 information a Fritz!Box cable model have, go to `http://<FRITZ BOX ADRESSE>:49000/tr64desc.xml` and copy the entire page and send it to me. Because I do not know, if there are any private information inside page (MAC-Address, Serial numbers, ... ) please send it via e-mail to me.

**Comment by rustyricky** [comment]
E-Mail is sent. There doesn't seem to be confidential data included at first glance.
If there is any more info required or tests to be done just let me know. I'm happy to help.

**Comment by mcktr** [comment]
Thanks a lot! :+1: 

You should have a mail with instructions for further tests.

**Comment by rustyricky** [comment]
I got the mail, thank you. I'll get back to you as soon as time allows it in the next few days.

**Comment by uclara** [comment]
Hi mcktr,

I have the same issue with my FRITZ!Box 6490 Cable. If you want I can also perform these tests.

Ulli

**Comment by mcktr** [comment]
Please have a look into the linked Pull Request. :)
