### ISSUE TITLE
2 questionas about upstreamrate & downstreamrate

### ISSUE THREAD

**Issue by syswombat** [mcktr/check_tr64_fritz#66]
hello
would it be possible to have the upstreamrate + downstreamrate as a Unit with negativ and possitive number. like down is negativ and upstream is possitiv.
so with gaphiphte  it would Show, if possible, a graph with both Information?

2) question
would it be possible to check this  upstreamrate + downstreamrate more  frequently?

have a nice day
vinc

**Comment by mcktr** [comment]
1. I am not sure what you mean. Can you please explain it a bit more? Why would you need a negative value for the downstreamrate for this?

2. You can modify the `check_interval` in your service apply rule.

**Comment by mcktr** [comment]
I suspect you mean something like this with your first question? 

![grafana - fritz box - chromium_008](https://user-images.githubusercontent.com/18580278/43090486-c93adc9a-8ea7-11e8-9264-0eaa9c385719.png)

You can achieve this by using modifiers in your graphing solution. For example I used `scale(-1)` for the downstream rate. I wouldn't change the output for `downstreamrate` or `upsreamrate` since the (positiv) output is valid.

**Comment by syswombat** [comment]
Ich wünschte mir so begnadet zu sein und coden zu können. genau das Bild meine ich

**Comment by syswombat** [comment]
did help too - hope it is not to short....

 38 object Service "Fritzbox 7490 downstreamrate" {
 39    host_name = "GW-01.kozo.ch"
 **40    check_interval = 15**
 41    check_command = "check_tr64_fritz-downstreamrate"
 42 }

**Comment by mcktr** [comment]
Since the questions seems to be resolved I'll close here.
