### ISSUE TITLE
Allow more than one function at once

### ISSUE THREAD

**Issue by fdellwing** [mcktr/check_tr64_fritz#77]
I looked at the code and know, that the functions have different endpoint urls, so this change would mean more than one request per script call. But as it is currently handled, the script does not help us at all, we would have to implement 5 different services just to get the information of one of our multiple Fritz!Boxes.

We would like to have at least the status, linkuptime, downstreamrate and upstreamrate bundled as information.

If you say, no way. I'll try to write a wrapper for this.

**Comment by mcktr** [comment]
Thanks for creating this feature request. 

Unfortunately such a feature would require to rewrite big parts of the check script (e.g. moving away from the switch/case statement and put the different checks in its own functions). Furthermore I am not quite happy with the check script anymore. It was good until it got more functions and got to complex for a shell script.

I moved forward and did a re-implementation of the check script in Golang, this can be found here: https://github.com/mcktr/check_fritz

Sooner or later I will stop actively developing this check script here, but I did not make a final decision here. For now I'll only do bug fixes. 

But I like your idea of having a check method which checks more than one information of a Fritz!Box. I will consider this idea for the Golang implementation. If you want you can follow the linked issue to join the conversation and/or follow the progress on this.

I close this issue here since I don't see that this will be implemented in any way soon (if ever).
